const bcrypt = require("bcrypt");

module.exports = [
  {
    id: 1,
    first_name: "Leon",
    last_name: "Williams",
    email: "test@test.com",
    username: "tennisChamp",
    password: bcrypt.hashSync("123", 6),
    sport: "Tennis",
    skill_level: "3",
  },
  {
    id: 2,
    first_name: "Wenzel",
    last_name: "Dashington",
    email: "wd@test.com",
    username: "badmingtonChamp",
    password: bcrypt.hashSync("123", 6),
    sport: "Badmington",
    skill_level: "1",
  },
  {
    id: 3,
    first_name: "Hom",
    last_name: "Tolland",
    email: "ht@test.com",
    username: "squashChamp",
    password: bcrypt.hashSync("123", 6),
    sport: "Squash",
    skill_level: "2",
  },
  {
    id: 4,
    first_name: "Tike",
    last_name: "Myson",
    email: "tm@test.com",
    username: "boxinfChamp",
    password: bcrypt.hashSync("123", 6),
    sport: "Squash",
    skill_level: "1",
  },
  {
    id: 5,
    first_name: "Lennifer",
    last_name: "Jawrence",
    email: "lj@test.com",
    username: "actingChamp",
    password: bcrypt.hashSync("123", 6),
    sport: "Tennis",
    skill_level: "4",
  },
];
