module.exports = [
  {
    id: 1,
    name: "London Fields Tennis Courts",
    location: "Richmond Rd, London E8 3QN",
    available_courts: 2,
  },
  {
    id: 2,
    name: "Southwark Park Tennis Courts",
    location: "Southwark Park, London SE16 2ET",
    available_courts: 3,
  },
  {
    id: 3,
    name: "Central Park Tennis Courts",
    location: "Central Park High St, London E6 6DY",
    available_courts: 1,
  },
  {
    id: 4,
    name: "Royal Automobile Club",
    location: "89-91 Pall Mall, Westminster, SW1Y 5HS",
    available_courts: 0,
  },
  {
    id: 5,
    name: "Elephant & Castle Leisure Centre",
    location: "22 Elephant & Castle, Southwark, SE1 6SQ",
    available_courts: 1,
  },
  {
    id: 6,
    name: "Polygon Badminton Club",
    location: "1 Norman St, London EC1V 3PU",
    available_courts: 1,
  },
  {
    id: 7,
    name: "Finsbury Leisure Centre",
    location: "Norman St, London EC1V 3PU",
    available_courts: 2,
  },
  {
    id: 8,
    name: "Wimbledon Tennis Club",
    location: "Church Rd, Wimbledon, London SW19 5AE",
    available_courts: 5,
  },
  {
    id: 9,
    name: "Hackney Downs Tennis Courts",
    location: "Hackney Downs Park, Downs Park Rd, London E5 8NP",
    available_courts: 4,
  },
  {
    id: 10,
    name: "Regent's Park Tennis Centre",
    location: "York Bridge, Inner Cir, London NW1 4NU",
    available_courts: 3,
  },
  {
    id: 11,
    name: "Islington Tennis Centre",
    location: "Market Rd, London N7 9PL",
    available_courts: 2,
  },
  {
    id: 12,
    name: "Battersea Park Tennis Courts",
    location: "Albert Bridge Rd, London SW11 4NJ",
    available_courts: 3,
  },
  {
    id: 13,
    name: "Greenwich Park Tennis Courts",
    location: "Great Cross Ave, London SE10 8QY",
    available_courts: 2,
  },
  {
    id: 14,
    name: "Clapham Common Tennis Courts",
    location: "Windmill Dr, London SW4 9DE",
    available_courts: 4,
  },
];
